# Copied files to public folder when build
copy:
    - bundle
    - favicon.ico
    - robots.txt
# I18n Support
lang:
    archive:
        en: ARCHIVE
        zh-cn: 归档

    tag:
        en: TAG
        zh-cn: 标签

    rss:
        en: RSS
        zh-cn: 订阅

    articles:
        en: Articles
        zh-cn: 篇文章

    updated:
        en: updated
        zh-cn: 更新
    prev_page:
        en: Prev Page
        zh-cn: ◀ 上一页
    next_page:
        en: Next Page
        zh-cn: 下一页 ▶
    prev_reading:
        en: Prev Reading
        zh-cn: ◀ 上一篇
    next_reading:
        en: Next Reading
        zh-cn: 下一篇 ▶
    top:
        en: TOP
        zh-cn: 置顶

    search:
        en: Search
        zh-cn: 搜索
    since_year:
        en: " years ago"
        zh-cn: 年前

    since_month:
        en: " months ago"
        zh-cn: 个月前
    since_day:
        en: " days ago"
        zh-cn: 天前
    since_hour:
        en: " hours ago"
        zh-cn: 小时前
    since_minute:
        en: " minutes ago"
        zh-cn: 分钟前
    since_second:
        en: " seconds ago"
        zh-cn: 秒前
    about:
        en: "About"
        zh-cn: 关于
    friend:
        zh-cn: 友链
    tool:
        zh-cn: 工具
        en: Tool
